version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6666:6379"
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  web:
    build:
      context: ./srcs
      dockerfile: ./Dockerfile
      args:
        DB_HOST: ${DB_HOST}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_PORT: ${DB_PORT}
    working_dir: /code/srcs
    command: sh ./scripts/entrypoint.sh
    #command: tail -f /dev/null
    restart: always
    volumes:
      - .:/code
      - socket_volume:/tmp
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:1.19
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - socket_volume:/tmp
      - .:/code
    depends_on:
      - web

volumes:
  db:
  socket_volume:
