# Generated by Django 3.2.25 on 2024-04-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0002_auto_20240426_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isTwoStepEmailAuthEnabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verificationEmailCode',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
