# Generated by Django 3.2.25 on 2024-04-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0003_userprofile_friendlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friendRequestList',
            field=models.ManyToManyField(blank=True, related_name='_pingpong_userprofile_friendRequestList_+', to='pingpong.UserProfile'),
        ),
    ]
